### ISSUE TITLE
bug: results subdir architecture bug?

### ISSUE THREAD

**Issue by AngryMaciek** [zavolanlab/zarp#34] opened 2021-11-12 15:13 UTC
While @meric466 run the test data me and @mkatsanto discovered that there probably is a bug in the results directory architecture.
Under `results/samples` we have per sample results directory. However, besides each sample `s` we have another directory `s.se` which contains only `sort_genomic_alignments_samtools` subdir. We are probably not evaluating wildcards properly at some rule...

**Comment by fgypas** [comment] 2021-11-12 16:57
So could this be due to this line?
https://github.com/zavolanlab/zarp/blob/dev/workflow/Snakefile#L674

**Comment by AngryMaciek** [comment] 2021-11-12 22:41
Hmm, could be... looks like it. One level of dir is missing, right?

**Comment by ninsch3000** [comment] 2022-03-16 13:14
hi @fgypas , I can move the `s.se` directory into `map_genome` at the [indicated line](https://github.com/zavolanlab/zarp/blob/dev/workflow/Snakefile#L674), which makes more sense. However, the `temp()` directive you specified doesn't seem to work, as the directory is still there after the run. I'm wondering now whether you remember why you are using the `-T` flag in `samtools sort` at all. The [samtools sort manual](http://www.htslib.org/doc/samtools-sort.html) states that "By default, any temporary files are written alongside the output file, as out.bam.tmp.nnnn.bam [...]". What's the reason we don't want the default behaviour?   

Please let me know, then I'll  either remove `-T` and `prefix_temp_dir`, or try to make the `temp()` directive work

**Comment by fgypas** [comment] 2022-03-16 13:26
I don't remember now, but if it the temp files are written in the same directory as output files then it's fine to use the default behaviour. The question is also if we need the {seqmode} wildcard? Can you please have a look at that as well?

**Comment by ninsch3000** [comment] 2022-03-16 13:53
Sure, I will

**Comment by ninsch3000** [comment] 2022-03-16 16:12
The `temp()` directive DOES work, I didn't realize the profile is set to not delete temp files, my bad.   

As for the `{seqmode}` wildcard, I'll create a new issue, because potentially it can be removed completely.

**Comment by mkatsanto** [comment] 2022-03-16 16:17
Hi, actually this issue was opened exactly for the suffix. The temp dir related issues have been fixed by @AngryMaciek and the branch is reviewed. So maybe use this issue for the suffix @ninsch3000 ?

**Comment by ninsch3000** [comment] 2022-03-16 16:31
hi @mkatsanto , I'm not sure what you mean. Here's what I mean:   
- when I said [above](https://github.com/zavolanlab/zarp/issues/34#issuecomment-1069114913) that `temp()` isn't working, I was WRONG. It was just because I didn't realize it was set to `notemp`
- For what Foivos said [above](https://github.com/zavolanlab/zarp/issues/34#issuecomment-1069127903) I created a new issue #60 because it is a separate issue.
- this issue here is for cleaning up the results directory architecture, which I am doing.

**Comment by ninsch3000** [comment] 2022-03-16 17:05
No please don't. The issue is solved. I will push in a minute after I have run all tests

**Closed** 2022-03-16 20:21 UTC
Labels: bug, good first issue
