### ISSUE TITLE
WorkflowError: Python package jinja2 must be installed to create reports.

### ISSUE THREAD

**Issue by noepozzan** [zavolanlab/zarp#57] opened 2022-03-16 08:25 UTC
**Describe the bug**
When testing the workflow with: bash tests/test_integration_workflow/test.slurm.sh or bash tests/test_integration_workflow/test.slurm.sh, jinja2 is not found?

**To Reproduce**
When running either of the commands above in the zarp conda env.
jinja2 should be available.

<img width="1440" alt="Screenshot 2022-03-16 at 09 23 55" src="https://user-images.githubusercontent.com/53306902/158547587-607553b8-016c-445d-94bf-622fd06f051d.png">

<img width="1440" alt="Screenshot 2022-03-16 at 09 18 24" src="https://user-images.githubusercontent.com/53306902/158547571-a6840447-dfd7-44c9-b6f3-e356f82e1f7b.png">

**Comment by AngryMaciek** [comment] 2022-03-16 08:31
Duplicate of #52, closing.

Also: please do not post sensitive data (scicore internal filesystem structure) on GitHub. It would be best to delete this screenshot ASAP.

**Closed by AngryMaciek** 2022-03-16 08:31 UTC
